version: '3'

services:
    server:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        restart: unless-stopped
        volumes:
            - .:/server/
        ports:
            - ${PORT}:8000
        env_file:
            - .env
