# Generated by Django 4.1.5 on 2023-01-03 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_alter_payment_options_payment_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-created',)},
        ),
    ]
